export const data = [
  {
    surveyname: "mfq",
    questiontext: "Caring for people who have suffered is an important virtue.",
    scaletype: "radiogroup",
    varname: "mfq_1",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I believe that compassion for those who are suffering is one of the most crucial virtues.",
    scaletype: "radiogroup",
    varname: "mfq_2",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "We should all care for people who are in emotional pain.",
    scaletype: "radiogroup",
    varname: "mfq_3",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I am empathetic toward those people who have suffered in their lives.",
    scaletype: "radiogroup",
    varname: "mfq_4",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "Everyone should try to comfort people who are going through something hard.",
    scaletype: "radiogroup",
    varname: "mfq_5",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "It pains me when I see someone ignoring the needs of another human being.",
    scaletype: "radiogroup",
    varname: "mfq_6",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "The world would be a better place if everyone made the same amount of money.",
    scaletype: "radiogroup",
    varname: "mfq_7",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "Our society would have fewer problems if people had the same income.",
    scaletype: "radiogroup",
    varname: "mfq_8",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I believe that everyone should be given the same quantity of resources in life.",
    scaletype: "radiogroup",
    varname: "mfq_9",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I believe it would be ideal if everyone in society wound up with roughly the same amount of money.",
    scaletype: "radiogroup",
    varname: "mfq_10",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "When people work together toward a common goal, they should share the rewards equally, even if some worked harder on it.",
    scaletype: "radiogroup",
    varname: "mfq_11",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I get upset when some people have a lot more money than others in my country.",
    scaletype: "radiogroup",
    varname: "mfq_12",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I think people who are more hard-working should end up with more money.",
    scaletype: "radiogroup",
    varname: "mfq_13",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I think people should be rewarded in proportion to what they contribute.",
    scaletype: "radiogroup",
    varname: "mfq_14",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "The effort a worker puts into a job ought to be reflected in the size of a raise they receive.",
    scaletype: "radiogroup",
    varname: "mfq_15",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "It makes me happy when people are recognized on their merits.",
    scaletype: "radiogroup",
    varname: "mfq_16",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "In a fair society, those who work hard should live with higher standards of living.",
    scaletype: "radiogroup",
    varname: "mfq_17",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "I feel good when I see cheaters get caught and punished.",
    scaletype: "radiogroup",
    varname: "mfq_18",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I think children should be taught to be loyal to their country.",
    scaletype: "radiogroup",
    varname: "mfq_19",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "It upsets me when people have no loyalty to their country.",
    scaletype: "radiogroup",
    varname: "mfq_20",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "Everyone should love their own community.",
    scaletype: "radiogroup",
    varname: "mfq_21",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "Everyone should defend their country, if called upon.",
    scaletype: "radiogroup",
    varname: "mfq_22",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "Everyone should feel proud when a person in their community wins in an international competition.",
    scaletype: "radiogroup",
    varname: "mfq_23",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I believe the strength of a sports team comes from the loyalty of its members to each other.",
    scaletype: "radiogroup",
    varname: "mfq_24",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I think it is important for societies to cherish their traditional values.",
    scaletype: "radiogroup",
    varname: "mfq_25",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I feel that most traditions serve a valuable function in keeping society orderly",
    scaletype: "radiogroup",
    varname: "mfq_26",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "I think obedience to parents is an important virtue.",
    scaletype: "radiogroup",
    varname: "mfq_27",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "We all need to learn from our elders.",
    scaletype: "radiogroup",
    varname: "mfq_28",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I believe that one of the most important values to teach children is to have respect for authority.",
    scaletype: "radiogroup",
    varname: "mfq_29",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "I think having a strong leader is good for society.",
    scaletype: "radiogroup",
    varname: "mfq_30",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "I think the human body should be treated like a temple, housing something sacred within.",
    scaletype: "radiogroup",
    varname: "mfq_31",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "I believe chastity is an important virtue.",
    scaletype: "radiogroup",
    varname: "mfq_32",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "It upsets me when people use foul language like it is nothing.",
    scaletype: "radiogroup",
    varname: "mfq_33",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "If I found out that an acquaintance had an unusual but harmless sexual fetish I would feel uneasy about them",
    scaletype: "radiogroup",
    varname: "mfq_34",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext:
      "People should try to use natural medicines rather than chemically identical human-made ones.",
    scaletype: "radiogroup",
    varname: "mfq_35",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
  {
    surveyname: "mfq",
    questiontext: "I admire people who keep their virginity until marriage.",
    scaletype: "radiogroup",
    varname: "mfq_36",
    option1: "Strongly Disagree",
    option2: "Disagree",
    option3: "Slightly Disagree",
    option4: "Netural",
    option5: "Slightly Agree",
    option6: "Agree",
    option7: "Strongly Agree",
  },
];
